---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'CloudWatch Alarm to Slack - now with Chatbots'
Parameters:
  Threshold:
    Description: 'Alarm, if your monthly estimated charges are higher'
    Default: 1
    Type: Number
  WebhookURL:
    Description: 'Slack incoming webhook URL'
    Type: String
Resources:
  #SNS topics used for alerting (one for each stage)
  ProdAlertTopic:
    Type: 'AWS::SNS::Topic'
  SandboxAlertTopic:
    Type: 'AWS::SNS::Topic'

  #begin section Chatbot for slack
  SandboxChatbotForSlack:
    Type: 'AWS::Chatbot::SlackChannelConfiguration'
    Properties:
      ConfigurationName: slack-alerts-cf-based-sandbox
      SlackChannelId: C04014LS5LM
      SlackWorkspaceId: T01G8NEU517
      IamRoleArn: arn:aws:iam::aws:policy/ReadOnlyAccess
      SnsTopicArns:
        - !Ref SandboxAlertTopic
  ProdChatbotForSlack:
    Type: 'AWS::Chatbot::SlackChannelConfiguration'
    Properties:
      ConfigurationName: slack-alerts-cf-based-sandbox
      SlackChannelId: C02R76BP3R6
      SlackWorkspaceId: T01G8NEU517
      IamRoleArn: arn:aws:iam::aws:policy/ReadOnlyAccess
      SnsTopicArns:
        - !Ref ProdAlertTopic
  #end section Chatbot for slack

  #DEPRECATED - Delete?
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'handler.event'
      Runtime: 'nodejs14.x'
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookURL
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref ProdAlertTopic
  #I don't understand this billing alarm here. What has this to do with the connection to Slack? Delete?
  Alarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
        - !Ref ProdAlertTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: 'AWS/Billing'
      Period: 86400
      Statistic: Maximum
      Threshold: !Ref Threshold

Outputs:
  #DEPRECATED - Kept previous name for backward compatibility - when changing services, new name (with stage) should be used
  AlarmTopicArn:
    Description: ARN of the SNS topic than forwards alarms to Slack
    Value: !Ref ProdAlertTopic
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "prod", AlarmTopicArn ] ]
  ProdAlarmTopicArn:
    Description: ARN of the SNS topic than forwards alarms to Slack
    Value: !Ref ProdAlertTopic
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "prod", ProdAlarmTopicArn ] ]
  SandboxAlarmTopicArn:
    Description: ARN of the SNS topic than forwards alarms to Slack
    Value: !Ref SandboxAlertTopic
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", "sandbox", SandboxAlarmTopicArn ] ]